name: Sync to Hugging Face

on:
  push:
    branches: [main]  # Cambia se il tuo branch principale ha nome diverso

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git lfs install
          
          # Create a new orphan branch to start with clean history
          git checkout --orphan clean-main
          
          # Set up LFS tracking
          git lfs track "*.pdf"
          git lfs track "*.png"
          git lfs track "*.jpg"
          git lfs track "*.jpeg"
          
          # Add all files (binary files will now be tracked by LFS)
          git add .
          git commit -m "Initial commit with LFS support"
          
          # Force push the clean branch as main to HuggingFace
          git push --force https://Cucco2001:$HF_TOKEN@huggingface.co/spaces/Cucco2001/nutraicoach clean-main:main
